// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191124020632_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Core.Entities.Car", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberPlate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isWifiAvailable")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarTypeId");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Core.Entities.CarType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Seat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CarType");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Cost = 700000m,
                            Name = "Ford EcoSport",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "2",
                            Cost = 1500000m,
                            Name = "Ford Everest",
                            Seat = (byte)7
                        },
                        new
                        {
                            Id = "3",
                            Cost = 700000m,
                            Name = "Ford Fiesta",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "4",
                            Cost = 500000m,
                            Name = "Kia Morning",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "5",
                            Cost = 700000m,
                            Name = "Kia Cerato",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "6",
                            Cost = 1100000m,
                            Name = "Kia Sorento",
                            Seat = (byte)7
                        },
                        new
                        {
                            Id = "7",
                            Cost = 800000m,
                            Name = "Rondo",
                            Seat = (byte)7
                        },
                        new
                        {
                            Id = "8",
                            Cost = 1600000m,
                            Name = "Sendona",
                            Seat = (byte)8
                        },
                        new
                        {
                            Id = "9",
                            Cost = 100000m,
                            Name = "Camry",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "10",
                            Cost = 1200000m,
                            Name = "Fortuner",
                            Seat = (byte)7
                        },
                        new
                        {
                            Id = "11",
                            Cost = 700000m,
                            Name = "Innova",
                            Seat = (byte)7
                        },
                        new
                        {
                            Id = "12",
                            Cost = 900000m,
                            Name = "Toyota Corrola Altis",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "13",
                            Cost = 800000m,
                            Name = "Mazda 3",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "14",
                            Cost = 1200000m,
                            Name = "Mazda CX5",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "15",
                            Cost = 2000000m,
                            Name = "Mescedes CLA",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "16",
                            Cost = 2000000m,
                            Name = "Mescedes C200",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "17",
                            Cost = 2200000m,
                            Name = "Mescedes C250",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "18",
                            Cost = 700000m,
                            Name = "Honda City",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "19",
                            Cost = 800000m,
                            Name = "Honda City TOP",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "20",
                            Cost = 1200000m,
                            Name = "Chevrolet Blazetrailer",
                            Seat = (byte)7
                        },
                        new
                        {
                            Id = "21",
                            Cost = 600000m,
                            Name = "Vinfast Fadil",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "22",
                            Cost = 900000m,
                            Name = "Huyndai Kona",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "23",
                            Cost = 1400000m,
                            Name = "Peugoet",
                            Seat = (byte)5
                        },
                        new
                        {
                            Id = "24",
                            Cost = 1500000m,
                            Name = "Ford Tourneo",
                            Seat = (byte)7
                        },
                        new
                        {
                            Id = "25",
                            Cost = 1300000m,
                            Name = "Mazda 6",
                            Seat = (byte)4
                        },
                        new
                        {
                            Id = "26",
                            Cost = 1100000m,
                            Name = "Honda Civic",
                            Seat = (byte)5
                        });
                });

            modelBuilder.Entity("Core.Entities.Car", b =>
                {
                    b.HasOne("Core.Entities.CarType", "CarType")
                        .WithMany("Cars")
                        .HasForeignKey("CarTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
